Controllers/PostController.cs
using Blog.Models;
using Microsoft.AspNetCore.Mvc;
namespace Blog.Controllers
{
public class PostController : Controller
{
public IActionResult Cadastro()
{
return View();
} [
HttpPost]
public IActionResult Cadastro(Post novoPost)

{
    PostService service = new PostService();
    
    if(novoPost.Id != 0){
          service.atualizarPost(novoPost);
          
          ViewData["msg"]="Atualização realizado com sucesso";
        
        return RedirectToAction("Lista");
        }else{
    int novoId = service.CreatePost(novoPost);
    
    if(novoId != 0){
        ViewData["msg"]="cadastro realizado com sucesso";
    }else{
        ViewData["msg"]="falha no cadastro";
    }
                return RedirectToAction("Lista");
        }
        
}
public IActionResult editar(int id){
    PostService ps = new PostService();
    Post post = ps.GetPostDetail(id);
    //return View( ps.GetPostDetail(id));
    return View("Cadastro", post);
   
}

/* o codigo abaixo foi anulado, e a ação de atualizção agora 
vai compartilhar do  mesmo codigo da iaction cadastrar, e a view de cadastro 
economizando recurso computacional tanto no back end quanto no front and , 
[HttpPost]  
public IActionResult editar(Post post){
    PostService ps = new PostService();
    ps.atualizarPost(post);
     
     return RedirectToAction("Lista");
}
*/ 


public IActionResult Lista(string ordem, string q)
{
PostService service = new PostService();
        if(q == null){
        q = string.Empty;
        }

        if(ordem == null){
        ordem = "t";
        }
return View(service.GetPosts(q, ordem));
}




public IActionResult excluir(int id){
 PostService ps = new PostService();
Post postparadeletar = ps.GetPostDetail(id);
return View(postparadeletar);

}
[HttpPost]
public IActionResult excluir(int id,string decisao){
    if(decisao == "s"){
        PostService ps = new PostService();
 ps.DeletePost(id);
    }

    return RedirectToAction("Lista");
}

}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                              <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Cadastro">Cadastro</a>
                        </li>

                        </li>

                              <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Lista">Listar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Blog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutBlog.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scal
e=1.0" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/css/blog.css" />
</head>

<body>
    <header>
        <div id="title">
            <h1>Blog Notícias da Cidade</h1>
        </div>
        <nav id="menu">
            <ul>
                <li><a>Home</a></li>
                <li><a>Categorias</a></li>
                <li><a>Sobre</a></li>

                </li>

                <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Cadastro">Cadastro</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        © 2019 - Blog</a>
    </footer>
    @RenderSection("Scripts", required: false)
</body>

</html>