Controllers/ComentarioController.cs
using System;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class ComentarioController:Controller
    {
        [HttpPost]
public IActionResult Cadastrar(Comentario c)
{
ComentarioService service = new ComentarioService();
c.Data = DateTime.Now; //data do comentário é o momento em que ele foi cadastrado
service.CreateComentario(c);
return RedirectToAction("Index", "Home");
}
        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Blog.Models;

namespace Blog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(int p = 1) // esse parametro possibilita a paginação indica o numero da pagina que sera exibida
        {
            int quantidadeDEpostsPorPaginas = 3; // quantidade de posts por paginas
            PostService ps = new PostService();
            ICollection<Post> lista = ps.GetPostsFull(p,quantidadeDEpostsPorPaginas); 

            int quantidadePosts = ps.CountPost();
            ViewData["paginas"] = (int)Math.Ceiling((double)quantidadePosts/quantidadeDEpostsPorPaginas);

            return View(lista);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@model List<Post>
@{
    Layout = "_LayoutBlog";
    ViewData["Title"] = "Home Page";
}
<div>
    @foreach (Post item in Model)
    {
        <article id="post-@item.Id" class="post">

            <h2 class="post-title">@item.Titulo</h2>
            <span class="post-date">@item.Data</span>

            <div class="post-content">
                <p>@item.Texto</p>
            </div>

                @*<section id="comments-@item.Id" class="comments">

                        <h4>Comentários</h4>
                        <partial name="_ListaComentarios" model="@item.Comentarios" /><!-- importa a text area de _ListaComentarios-->
                        <partial name="_FormComentarios" model="@item.Id" /> <!-- importa a text area de _FormComentarios-->
                    </section>
                    *@
        </article>
        
    }
    @for(int i = 1; i <=(int)ViewData["paginas"];i++){ // paginação cria os links para as pginas 
        <a href="/?p=@i">@i,</a>

    }
</div>

Views/Home/_FormComentarios.cshtml
@model int
<form asp-action="Cadastrar" asp-controller="Comentario" method="POST"
class="form-comment">
<input type="hidden" name="PostId" value="@Model"/>
<input type="text" name="Autor" placeholder="Nome" class="comment-n
ame"/>
<textarea name="Conteudo" placeholder="Comentário" class="comment-t
ext" rows="4" cols="50"></textarea>
<input type="submit" value="Comentar"/>
</form>

Views/Home/_ListaComentarios.cshtml
@model ICollection<Comentario>
@foreach (Comentario comment in Model)
{
<h5>@comment.Autor - @comment.Data.ToString("dd/MM/yy HH:mm")</h5>
<p>@comment.Conteudo</p>
}